/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import view.menuheading;
import view.menuPenumpangg;
import view.menuPemesanann;
import view.menupesawat;
import view.menutikett;
/**
 *
 * @author SATYA
 */
public class frmtikett extends javax.swing.JFrame {

    /**
     * Creates new form frmtikett
     */
    public frmtikett() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kir = new javax.swing.JPanel();
        pn_k = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        btnPenumpang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnPesawat = new javax.swing.JButton();
        btn_Tiket = new javax.swing.JButton();
        pn_kanan = new javax.swing.JPanel();
        pn_konten = new javax.swing.JPanel();
        pn_mk = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_k.setBackground(new java.awt.Color(0, 153, 153));
        pn_k.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("WINGS HIGH");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Master Data");

        btnDashboard.setText("DASHBOARD");
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnPemesanan.setText("PEMESANAN");
        btnPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPemesananMouseClicked(evt);
            }
        });

        btnPenumpang.setText("PENUMPANG");
        btnPenumpang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPenumpangMouseClicked(evt);
            }
        });
        btnPenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenumpangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Tiket");

        btnPesawat.setText("PESAWAT");
        btnPesawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesawatMouseClicked(evt);
            }
        });

        btn_Tiket.setText("TIKET");
        btn_Tiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TiketMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_kLayout = new javax.swing.GroupLayout(pn_k);
        pn_k.setLayout(pn_kLayout);
        pn_kLayout.setHorizontalGroup(
            pn_kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnDashboard)
                    .addComponent(btnPemesanan)
                    .addComponent(btnPenumpang)
                    .addComponent(jLabel3)
                    .addComponent(btnPesawat)
                    .addComponent(btn_Tiket))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pn_kLayout.setVerticalGroup(
            pn_kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDashboard)
                .addGap(29, 29, 29)
                .addComponent(btnPemesanan)
                .addGap(31, 31, 31)
                .addComponent(btnPenumpang)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnPesawat)
                .addGap(26, 26, 26)
                .addComponent(btn_Tiket)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_kirLayout = new javax.swing.GroupLayout(pn_kir);
        pn_kir.setLayout(pn_kirLayout);
        pn_kirLayout.setHorizontalGroup(
            pn_kirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_kirLayout.setVerticalGroup(
            pn_kirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_k, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pn_kir, java.awt.BorderLayout.LINE_START);

        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_mk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn_mk.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_kontenLayout = new javax.swing.GroupLayout(pn_konten);
        pn_konten.setLayout(pn_kontenLayout);
        pn_kontenLayout.setHorizontalGroup(
            pn_kontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_mk, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        pn_kontenLayout.setVerticalGroup(
            pn_kontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_mk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_kanan.add(pn_konten, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        pn_mk.removeAll();
        pn_mk.add(new menuheading());
        pn_mk.repaint();
        pn_mk.revalidate();
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPemesananMouseClicked
        pn_mk.removeAll();
        pn_mk.add(new menuPemesanann());
        pn_mk.repaint();
        pn_mk.revalidate();
    }//GEN-LAST:event_btnPemesananMouseClicked

    private void btnPenumpangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenumpangMouseClicked
        pn_mk.removeAll();
        pn_mk.add(new menuPenumpangg());
        pn_mk.repaint();
        pn_mk.revalidate();
    }//GEN-LAST:event_btnPenumpangMouseClicked

    private void btnPesawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesawatMouseClicked
        pn_mk.removeAll();
        pn_mk.add(new menupesawat());
        pn_mk.repaint();
        pn_mk.revalidate();
    }//GEN-LAST:event_btnPesawatMouseClicked

    private void btn_TiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TiketMouseClicked
        pn_mk.removeAll();
        pn_mk.add(new menutikett());
        pn_mk.repaint();
        pn_mk.revalidate();
    }//GEN-LAST:event_btn_TiketMouseClicked

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnPenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenumpangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPenumpangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmtikett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmtikett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmtikett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmtikett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmtikett().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnPenumpang;
    private javax.swing.JButton btnPesawat;
    private javax.swing.JButton btn_Tiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pn_k;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kir;
    private javax.swing.JPanel pn_konten;
    private javax.swing.JPanel pn_mk;
    // End of variables declaration//GEN-END:variables
}
